//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributorPortal.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DistributorPortal.Resource.NotificationMessage", typeof(NotificationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License uploaded successfully.
        /// </summary>
        public static string AddLicense {
            get {
                return ResourceManager.GetString("AddLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add verified license or challan before placing the order.
        /// </summary>
        public static string AddVerifiedLicense {
            get {
                return ResourceManager.GetString("AddVerifiedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least add one quantity in products.
        /// </summary>
        public static string AtLeastAddOneQuantity {
            get {
                return ResourceManager.GetString("AtLeastAddOneQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint approved successfully.
        /// </summary>
        public static string ComplaintApproved {
            get {
                return ResourceManager.GetString("ComplaintApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint has rejected.
        /// </summary>
        public static string ComplaintRejected {
            get {
                return ResourceManager.GetString("ComplaintRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint resolved successfully.
        /// </summary>
        public static string ComplaintResolved {
            get {
                return ResourceManager.GetString("ComplaintResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully..
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while saving changes.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to received return.
        /// </summary>
        public static string FailedReturn {
            get {
                return ResourceManager.GetString("FailedReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size should not be greater than 5mb..
        /// </summary>
        public static string FileSizeAllowed {
            get {
                return ResourceManager.GetString("FileSizeAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only image, docx or pdf file is allowed..
        /// </summary>
        public static string FileTypeAllowed {
            get {
                return ResourceManager.GetString("FileTypeAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully..
        /// </summary>
        public static string FileUploadedSuccessfully {
            get {
                return ResourceManager.GetString("FileUploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved successfully..
        /// </summary>
        public static string FormStatusApproved {
            get {
                return ResourceManager.GetString("FormStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed successfully..
        /// </summary>
        public static string FormStatusCompleted {
            get {
                return ResourceManager.GetString("FormStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Excel file is allowed.
        /// </summary>
        public static string OnlyExcelFileAllowed {
            get {
                return ResourceManager.GetString("OnlyExcelFileAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order saved successfully.
        /// </summary>
        public static string OrderSaved {
            get {
                return ResourceManager.GetString("OrderSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order saved as draft successfully.
        /// </summary>
        public static string OrderSavedDraft {
            get {
                return ResourceManager.GetString("OrderSavedDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license has expired, but you are temporarily allowed to place the order..
        /// </summary>
        public static string OrderTemporarilyAllowed {
            get {
                return ResourceManager.GetString("OrderTemporarilyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment saved successfully.
        /// </summary>
        public static string PaymentSaved {
            get {
                return ResourceManager.GetString("PaymentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment verified successfully.
        /// </summary>
        public static string PaymentVerified {
            get {
                return ResourceManager.GetString("PaymentVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully received return product.
        /// </summary>
        public static string ReceivedReturn {
            get {
                return ResourceManager.GetString("ReceivedReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the information below. The field labels marked with * are required input fields..
        /// </summary>
        public static string RequiredFieldsValidation {
            get {
                return ResourceManager.GetString("RequiredFieldsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully.
        /// </summary>
        public static string ResetPasswordSuccessfully {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved successfully.
        /// </summary>
        public static string Resolved {
            get {
                return ResourceManager.GetString("Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully..
        /// </summary>
        public static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced successfully.
        /// </summary>
        public static string SyncedSuccessfully {
            get {
                return ResourceManager.GetString("SyncedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Challan saved successfully.
        /// </summary>
        public static string TaxChallanSaved {
            get {
                return ResourceManager.GetString("TaxChallanSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to approve order.
        /// </summary>
        public static string UnableToApproveOrder {
            get {
                return ResourceManager.GetString("UnableToApproveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully..
        /// </summary>
        public static string UpdateSuccessfully {
            get {
                return ResourceManager.GetString("UpdateSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
