//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPConfigurationAPI.DPPendingOrdersRequest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.sami.com/DPPendingOrders", ConfigurationName="DPPendingOrdersRequest.DPPendingOrdersRequest_Out")]
    public interface DPPendingOrdersRequest_Out {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:sap-com:document:sap:rfc:functions) of message DPPendingOrdersRequest_OutRequest does not match the default value (https://www.sami.com/DPPendingOrders)
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse DPPendingOrdersRequest_Out(SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse> DPPendingOrdersRequest_OutAsync(SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_PENDING_ORDER_OUT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATNRField;
        
        private decimal kWMENGField;
        
        private bool kWMENGFieldSpecified;
        
        private decimal lFIMGField;
        
        private bool lFIMGFieldSpecified;
        
        private decimal pENDINGField;
        
        private bool pENDINGFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal KWMENG {
            get {
                return this.kWMENGField;
            }
            set {
                this.kWMENGField = value;
                this.RaisePropertyChanged("KWMENG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KWMENGSpecified {
            get {
                return this.kWMENGFieldSpecified;
            }
            set {
                this.kWMENGFieldSpecified = value;
                this.RaisePropertyChanged("KWMENGSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal LFIMG {
            get {
                return this.lFIMGField;
            }
            set {
                this.lFIMGField = value;
                this.RaisePropertyChanged("LFIMG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LFIMGSpecified {
            get {
                return this.lFIMGFieldSpecified;
            }
            set {
                this.lFIMGFieldSpecified = value;
                this.RaisePropertyChanged("LFIMGSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal PENDING {
            get {
                return this.pENDINGField;
            }
            set {
                this.pENDINGField = value;
                this.RaisePropertyChanged("PENDING");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PENDINGSpecified {
            get {
                return this.pENDINGFieldSpecified;
            }
            set {
                this.pENDINGFieldSpecified = value;
                this.RaisePropertyChanged("PENDINGSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZSD_GET_PENDING_ORDERS", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class DPPendingOrdersRequest_OutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_DISTRIBUTOR;
        
        public DPPendingOrdersRequest_OutRequest() {
        }
        
        public DPPendingOrdersRequest_OutRequest(string IV_DISTRIBUTOR) {
            this.IV_DISTRIBUTOR = IV_DISTRIBUTOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZSD_GET_PENDING_ORDERS.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class DPPendingOrdersRequest_OutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SAPConfigurationAPI.DPPendingOrdersRequest.ZST_PENDING_ORDER_OUT[] E_ORDERS;
        
        public DPPendingOrdersRequest_OutResponse() {
        }
        
        public DPPendingOrdersRequest_OutResponse(SAPConfigurationAPI.DPPendingOrdersRequest.ZST_PENDING_ORDER_OUT[] E_ORDERS) {
            this.E_ORDERS = E_ORDERS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DPPendingOrdersRequest_OutChannel : SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DPPendingOrdersRequest_OutClient : System.ServiceModel.ClientBase<SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_Out>, SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_Out {
        
        public DPPendingOrdersRequest_OutClient() {
        }
        
        public DPPendingOrdersRequest_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DPPendingOrdersRequest_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DPPendingOrdersRequest_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DPPendingOrdersRequest_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_Out.DPPendingOrdersRequest_Out(SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest request) {
            return base.Channel.DPPendingOrdersRequest_Out(request);
        }
        
        public SAPConfigurationAPI.DPPendingOrdersRequest.ZST_PENDING_ORDER_OUT[] DPPendingOrdersRequest_Out(string IV_DISTRIBUTOR) {
            SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest inValue = new SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest();
            inValue.IV_DISTRIBUTOR = IV_DISTRIBUTOR;
            SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse retVal = ((SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_Out)(this)).DPPendingOrdersRequest_Out(inValue);
            return retVal.E_ORDERS;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse> SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_Out.DPPendingOrdersRequest_OutAsync(SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest request) {
            return base.Channel.DPPendingOrdersRequest_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse> DPPendingOrdersRequest_OutAsync(string IV_DISTRIBUTOR) {
            SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest inValue = new SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest();
            inValue.IV_DISTRIBUTOR = IV_DISTRIBUTOR;
            return ((SAPConfigurationAPI.DPPendingOrdersRequest.DPPendingOrdersRequest_Out)(this)).DPPendingOrdersRequest_OutAsync(inValue);
        }
    }
}
