//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRDProductWisePriceDiscount
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sami.com/DP", ConfigurationName="PRDProductWisePriceDiscount.DIS_REQ_OUT")]
    public interface DIS_REQ_OUT
    {
        
        // CODEGEN: Generating message contract since the operation DIS_REQ_OUT is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PRDProductWisePriceDiscount.DIS_REQ_OUTResponse DIS_REQ_OUT(PRDProductWisePriceDiscount.DIS_REQ_OUTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<PRDProductWisePriceDiscount.DIS_REQ_OUTResponse> DIS_REQ_OUTAsync(PRDProductWisePriceDiscount.DIS_REQ_OUTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sami.com/DP")]
    public partial class MAT_DISC_OUT
    {
        
        private MAT_DISC_OUTItem[] mAT_DTLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MAT_DISC_OUTItem[] MAT_DTL
        {
            get
            {
                return this.mAT_DTLField;
            }
            set
            {
                this.mAT_DTLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sami.com/DP")]
    public partial class MAT_DISC_OUTItem
    {
        
        private string mATNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATNR
        {
            get
            {
                return this.mATNRField;
            }
            set
            {
                this.mATNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSS_DISPRZ_DIST
    {
        
        private string kUNNRField;
        
        private string mATNRField;
        
        private string mAKTXField;
        
        private string mVGR1Field;
        
        private string mVGR1TField;
        
        private string mVGR2Field;
        
        private string mVGR2TField;
        
        private string mVGR3Field;
        
        private string mVGR3TField;
        
        private string mVGR4Field;
        
        private string mVGR4TField;
        
        private string mVGR5Field;
        
        private string mVGR5TField;
        
        private string wRKSTField;
        
        private decimal kBETRField;
        
        private bool kBETRFieldSpecified;
        
        private decimal cARTONField;
        
        private bool cARTONFieldSpecified;
        
        private decimal dISCOUNTField;
        
        private bool dISCOUNTFieldSpecified;
        
        private string mTPOSField;
        
        private decimal sfField;
        
        private bool sfFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string KUNNR
        {
            get
            {
                return this.kUNNRField;
            }
            set
            {
                this.kUNNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MATNR
        {
            get
            {
                return this.mATNRField;
            }
            set
            {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MAKTX
        {
            get
            {
                return this.mAKTXField;
            }
            set
            {
                this.mAKTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MVGR1
        {
            get
            {
                return this.mVGR1Field;
            }
            set
            {
                this.mVGR1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MVGR1T
        {
            get
            {
                return this.mVGR1TField;
            }
            set
            {
                this.mVGR1TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MVGR2
        {
            get
            {
                return this.mVGR2Field;
            }
            set
            {
                this.mVGR2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MVGR2T
        {
            get
            {
                return this.mVGR2TField;
            }
            set
            {
                this.mVGR2TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MVGR3
        {
            get
            {
                return this.mVGR3Field;
            }
            set
            {
                this.mVGR3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MVGR3T
        {
            get
            {
                return this.mVGR3TField;
            }
            set
            {
                this.mVGR3TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MVGR4
        {
            get
            {
                return this.mVGR4Field;
            }
            set
            {
                this.mVGR4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string MVGR4T
        {
            get
            {
                return this.mVGR4TField;
            }
            set
            {
                this.mVGR4TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string MVGR5
        {
            get
            {
                return this.mVGR5Field;
            }
            set
            {
                this.mVGR5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string MVGR5T
        {
            get
            {
                return this.mVGR5TField;
            }
            set
            {
                this.mVGR5TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string WRKST
        {
            get
            {
                return this.wRKSTField;
            }
            set
            {
                this.wRKSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal KBETR
        {
            get
            {
                return this.kBETRField;
            }
            set
            {
                this.kBETRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KBETRSpecified
        {
            get
            {
                return this.kBETRFieldSpecified;
            }
            set
            {
                this.kBETRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal CARTON
        {
            get
            {
                return this.cARTONField;
            }
            set
            {
                this.cARTONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CARTONSpecified
        {
            get
            {
                return this.cARTONFieldSpecified;
            }
            set
            {
                this.cARTONFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal DISCOUNT
        {
            get
            {
                return this.dISCOUNTField;
            }
            set
            {
                this.dISCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DISCOUNTSpecified
        {
            get
            {
                return this.dISCOUNTFieldSpecified;
            }
            set
            {
                this.dISCOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string MTPOS
        {
            get
            {
                return this.mTPOSField;
            }
            set
            {
                this.mTPOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public decimal SF
        {
            get
            {
                return this.sfField;
            }
            set
            {
                this.sfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SFSpecified
        {
            get
            {
                return this.sfFieldSpecified;
            }
            set
            {
                this.sfFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSS_PRICE_DISCOUNT_DISTWISEResponse
    {
        
        private ZSS_DISPRZ_DIST[] dIST_WISEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSS_DISPRZ_DIST[] DIST_WISE
        {
            get
            {
                return this.dIST_WISEField;
            }
            set
            {
                this.dIST_WISEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DIS_REQ_OUTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sami.com/DP", Order=0)]
        public PRDProductWisePriceDiscount.MAT_DISC_OUT DIS_REQ_IN;
        
        public DIS_REQ_OUTRequest()
        {
        }
        
        public DIS_REQ_OUTRequest(PRDProductWisePriceDiscount.MAT_DISC_OUT DIS_REQ_IN)
        {
            this.DIS_REQ_IN = DIS_REQ_IN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DIS_REQ_OUTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZSS_PRICE_DISCOUNT_DISTWISE.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ZSS_PRICE_DISCOUNT_DISTWISE.Response")]
        public PRDProductWisePriceDiscount.ZSS_PRICE_DISCOUNT_DISTWISEResponse ZSS_PRICE_DISCOUNT_DISTWISEResponse;
        
        public DIS_REQ_OUTResponse()
        {
        }
        
        public DIS_REQ_OUTResponse(PRDProductWisePriceDiscount.ZSS_PRICE_DISCOUNT_DISTWISEResponse ZSS_PRICE_DISCOUNT_DISTWISEResponse)
        {
            this.ZSS_PRICE_DISCOUNT_DISTWISEResponse = ZSS_PRICE_DISCOUNT_DISTWISEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DIS_REQ_OUTChannel : PRDProductWisePriceDiscount.DIS_REQ_OUT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DIS_REQ_OUTClient : System.ServiceModel.ClientBase<PRDProductWisePriceDiscount.DIS_REQ_OUT>, PRDProductWisePriceDiscount.DIS_REQ_OUT
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DIS_REQ_OUTClient(EndpointConfiguration endpointConfiguration) : 
                base(DIS_REQ_OUTClient.GetBindingForEndpoint(endpointConfiguration), DIS_REQ_OUTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DIS_REQ_OUTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DIS_REQ_OUTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DIS_REQ_OUTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DIS_REQ_OUTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DIS_REQ_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRDProductWisePriceDiscount.DIS_REQ_OUTResponse PRDProductWisePriceDiscount.DIS_REQ_OUT.DIS_REQ_OUT(PRDProductWisePriceDiscount.DIS_REQ_OUTRequest request)
        {
            return base.Channel.DIS_REQ_OUT(request);
        }
        
        public PRDProductWisePriceDiscount.ZSS_PRICE_DISCOUNT_DISTWISEResponse DIS_REQ_OUT(PRDProductWisePriceDiscount.MAT_DISC_OUT DIS_REQ_IN)
        {
            PRDProductWisePriceDiscount.DIS_REQ_OUTRequest inValue = new PRDProductWisePriceDiscount.DIS_REQ_OUTRequest();
            inValue.DIS_REQ_IN = DIS_REQ_IN;
            PRDProductWisePriceDiscount.DIS_REQ_OUTResponse retVal = ((PRDProductWisePriceDiscount.DIS_REQ_OUT)(this)).DIS_REQ_OUT(inValue);
            return retVal.ZSS_PRICE_DISCOUNT_DISTWISEResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PRDProductWisePriceDiscount.DIS_REQ_OUTResponse> PRDProductWisePriceDiscount.DIS_REQ_OUT.DIS_REQ_OUTAsync(PRDProductWisePriceDiscount.DIS_REQ_OUTRequest request)
        {
            return base.Channel.DIS_REQ_OUTAsync(request);
        }
        
        public System.Threading.Tasks.Task<PRDProductWisePriceDiscount.DIS_REQ_OUTResponse> DIS_REQ_OUTAsync(PRDProductWisePriceDiscount.MAT_DISC_OUT DIS_REQ_IN)
        {
            PRDProductWisePriceDiscount.DIS_REQ_OUTRequest inValue = new PRDProductWisePriceDiscount.DIS_REQ_OUTRequest();
            inValue.DIS_REQ_IN = DIS_REQ_IN;
            return ((PRDProductWisePriceDiscount.DIS_REQ_OUT)(this)).DIS_REQ_OUTAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://s049sappoprd.samipharma.com.pk:51100/XISOAPAdapter/MessageServlet?senderPa" +
                        "rty=&senderService=NSAP_PRD&receiverParty=&receiverService=&interface=DIS_REQ_OU" +
                        "T&interfaceNamespace=http%3A%2F%2Fwww.sami.com%2FDP");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://s049sappoprd.samipharma.com.pk:51101/XISOAPAdapter/MessageServlet?senderP" +
                        "arty=&senderService=NSAP_PRD&receiverParty=&receiverService=&interface=DIS_REQ_O" +
                        "UT&interfaceNamespace=http%3A%2F%2Fwww.sami.com%2FDP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
