//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRDOrderStatusRequest
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sami.com/DP", ConfigurationName="PRDOrderStatusRequest.Ord_status_Request_OUT")]
    public interface Ord_status_Request_OUT
    {
        
        // CODEGEN: Generating message contract since the operation Ord_status_Request_OUT is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PRDOrderStatusRequest.Ord_status_Request_OUTResponse Ord_status_Request_OUT(PRDOrderStatusRequest.Ord_status_Request_OUTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<PRDOrderStatusRequest.Ord_status_Request_OUTResponse> Ord_status_Request_OUTAsync(PRDOrderStatusRequest.Ord_status_Request_OUTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sami.com/DP")]
    public partial class Ord_status_Request_IN
    {
        
        private Ord_status_Request_main[] oRDERSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ord_status_Request_main[] ORDERS
        {
            get
            {
                return this.oRDERSField;
            }
            set
            {
                this.oRDERSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sami.com/DP")]
    public partial class Ord_status_Request_main
    {
        
        private string vBELNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VBELN
        {
            get
            {
                return this.vBELNField;
            }
            set
            {
                this.vBELNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class VBUK
    {
        
        private string mANDTField;
        
        private string vBELNField;
        
        private string rFSTKField;
        
        private string rFGSKField;
        
        private string bESTKField;
        
        private string lFSTKField;
        
        private string lFGSKField;
        
        private string wBSTKField;
        
        private string fKSTKField;
        
        private string fKSAKField;
        
        private string bUCHKField;
        
        private string aBSTKField;
        
        private string gBSTKField;
        
        private string kOSTKField;
        
        private string lVSTKField;
        
        private string uVALSField;
        
        private string uVVLSField;
        
        private string uVFASField;
        
        private string uVALLField;
        
        private string uVVLKField;
        
        private string uVFAKField;
        
        private string uVPRSField;
        
        private string vBTYPField;
        
        private string vBOBJField;
        
        private string aEDATField;
        
        private string fKIVKField;
        
        private string rELIKField;
        
        private string uVK01Field;
        
        private string uVK02Field;
        
        private string uVK03Field;
        
        private string uVK04Field;
        
        private string uVK05Field;
        
        private string uVS01Field;
        
        private string uVS02Field;
        
        private string uVS03Field;
        
        private string uVS04Field;
        
        private string uVS05Field;
        
        private string pKSTKField;
        
        private string cMPSAField;
        
        private string cMPSBField;
        
        private string cMPSCField;
        
        private string cMPSDField;
        
        private string cMPSEField;
        
        private string cMPSFField;
        
        private string cMPSGField;
        
        private string cMPSHField;
        
        private string cMPSIField;
        
        private string cMPSJField;
        
        private string cMPSKField;
        
        private string cMPSLField;
        
        private string cMPS0Field;
        
        private string cMPS1Field;
        
        private string cMPS2Field;
        
        private string cMGSTField;
        
        private string tRSTAField;
        
        private string kOQUKField;
        
        private string cOSTAField;
        
        private string sAPRLField;
        
        private string uVPASField;
        
        private string uVPISField;
        
        private string uVWASField;
        
        private string uVPAKField;
        
        private string uVPIKField;
        
        private string uVWAKField;
        
        private string uVGEKField;
        
        private string cMPSMField;
        
        private string dCSTKField;
        
        private string vESTKField;
        
        private string vLSTKField;
        
        private string rRSTAField;
        
        private string bLOCKField;
        
        private string fSSTKField;
        
        private string lSSTKField;
        
        private string sPSTGField;
        
        private string pDSTKField;
        
        private string fMSTKField;
        
        private string mANEKField;
        
        private string sPE_TMPIDField;
        
        private string hDALLField;
        
        private string hDALSField;
        
        private string cMPS_CMField;
        
        private string cMPS_TEField;
        
        private string vBTYP_EXTField;
        
        private string fSH_AR_STAT_HDRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MANDT
        {
            get
            {
                return this.mANDTField;
            }
            set
            {
                this.mANDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VBELN
        {
            get
            {
                return this.vBELNField;
            }
            set
            {
                this.vBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string RFSTK
        {
            get
            {
                return this.rFSTKField;
            }
            set
            {
                this.rFSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RFGSK
        {
            get
            {
                return this.rFGSKField;
            }
            set
            {
                this.rFGSKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string BESTK
        {
            get
            {
                return this.bESTKField;
            }
            set
            {
                this.bESTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LFSTK
        {
            get
            {
                return this.lFSTKField;
            }
            set
            {
                this.lFSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string LFGSK
        {
            get
            {
                return this.lFGSKField;
            }
            set
            {
                this.lFGSKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string WBSTK
        {
            get
            {
                return this.wBSTKField;
            }
            set
            {
                this.wBSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string FKSTK
        {
            get
            {
                return this.fKSTKField;
            }
            set
            {
                this.fKSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string FKSAK
        {
            get
            {
                return this.fKSAKField;
            }
            set
            {
                this.fKSAKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string BUCHK
        {
            get
            {
                return this.bUCHKField;
            }
            set
            {
                this.bUCHKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ABSTK
        {
            get
            {
                return this.aBSTKField;
            }
            set
            {
                this.aBSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string GBSTK
        {
            get
            {
                return this.gBSTKField;
            }
            set
            {
                this.gBSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string KOSTK
        {
            get
            {
                return this.kOSTKField;
            }
            set
            {
                this.kOSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string LVSTK
        {
            get
            {
                return this.lVSTKField;
            }
            set
            {
                this.lVSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string UVALS
        {
            get
            {
                return this.uVALSField;
            }
            set
            {
                this.uVALSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string UVVLS
        {
            get
            {
                return this.uVVLSField;
            }
            set
            {
                this.uVVLSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string UVFAS
        {
            get
            {
                return this.uVFASField;
            }
            set
            {
                this.uVFASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string UVALL
        {
            get
            {
                return this.uVALLField;
            }
            set
            {
                this.uVALLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string UVVLK
        {
            get
            {
                return this.uVVLKField;
            }
            set
            {
                this.uVVLKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string UVFAK
        {
            get
            {
                return this.uVFAKField;
            }
            set
            {
                this.uVFAKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string UVPRS
        {
            get
            {
                return this.uVPRSField;
            }
            set
            {
                this.uVPRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string VBTYP
        {
            get
            {
                return this.vBTYPField;
            }
            set
            {
                this.vBTYPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string VBOBJ
        {
            get
            {
                return this.vBOBJField;
            }
            set
            {
                this.vBOBJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string AEDAT
        {
            get
            {
                return this.aEDATField;
            }
            set
            {
                this.aEDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string FKIVK
        {
            get
            {
                return this.fKIVKField;
            }
            set
            {
                this.fKIVKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string RELIK
        {
            get
            {
                return this.rELIKField;
            }
            set
            {
                this.rELIKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string UVK01
        {
            get
            {
                return this.uVK01Field;
            }
            set
            {
                this.uVK01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string UVK02
        {
            get
            {
                return this.uVK02Field;
            }
            set
            {
                this.uVK02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string UVK03
        {
            get
            {
                return this.uVK03Field;
            }
            set
            {
                this.uVK03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string UVK04
        {
            get
            {
                return this.uVK04Field;
            }
            set
            {
                this.uVK04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string UVK05
        {
            get
            {
                return this.uVK05Field;
            }
            set
            {
                this.uVK05Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string UVS01
        {
            get
            {
                return this.uVS01Field;
            }
            set
            {
                this.uVS01Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string UVS02
        {
            get
            {
                return this.uVS02Field;
            }
            set
            {
                this.uVS02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string UVS03
        {
            get
            {
                return this.uVS03Field;
            }
            set
            {
                this.uVS03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string UVS04
        {
            get
            {
                return this.uVS04Field;
            }
            set
            {
                this.uVS04Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string UVS05
        {
            get
            {
                return this.uVS05Field;
            }
            set
            {
                this.uVS05Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string PKSTK
        {
            get
            {
                return this.pKSTKField;
            }
            set
            {
                this.pKSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string CMPSA
        {
            get
            {
                return this.cMPSAField;
            }
            set
            {
                this.cMPSAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string CMPSB
        {
            get
            {
                return this.cMPSBField;
            }
            set
            {
                this.cMPSBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string CMPSC
        {
            get
            {
                return this.cMPSCField;
            }
            set
            {
                this.cMPSCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string CMPSD
        {
            get
            {
                return this.cMPSDField;
            }
            set
            {
                this.cMPSDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string CMPSE
        {
            get
            {
                return this.cMPSEField;
            }
            set
            {
                this.cMPSEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string CMPSF
        {
            get
            {
                return this.cMPSFField;
            }
            set
            {
                this.cMPSFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string CMPSG
        {
            get
            {
                return this.cMPSGField;
            }
            set
            {
                this.cMPSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string CMPSH
        {
            get
            {
                return this.cMPSHField;
            }
            set
            {
                this.cMPSHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string CMPSI
        {
            get
            {
                return this.cMPSIField;
            }
            set
            {
                this.cMPSIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string CMPSJ
        {
            get
            {
                return this.cMPSJField;
            }
            set
            {
                this.cMPSJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string CMPSK
        {
            get
            {
                return this.cMPSKField;
            }
            set
            {
                this.cMPSKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string CMPSL
        {
            get
            {
                return this.cMPSLField;
            }
            set
            {
                this.cMPSLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string CMPS0
        {
            get
            {
                return this.cMPS0Field;
            }
            set
            {
                this.cMPS0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string CMPS1
        {
            get
            {
                return this.cMPS1Field;
            }
            set
            {
                this.cMPS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string CMPS2
        {
            get
            {
                return this.cMPS2Field;
            }
            set
            {
                this.cMPS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string CMGST
        {
            get
            {
                return this.cMGSTField;
            }
            set
            {
                this.cMGSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string TRSTA
        {
            get
            {
                return this.tRSTAField;
            }
            set
            {
                this.tRSTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string KOQUK
        {
            get
            {
                return this.kOQUKField;
            }
            set
            {
                this.kOQUKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string COSTA
        {
            get
            {
                return this.cOSTAField;
            }
            set
            {
                this.cOSTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string SAPRL
        {
            get
            {
                return this.sAPRLField;
            }
            set
            {
                this.sAPRLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string UVPAS
        {
            get
            {
                return this.uVPASField;
            }
            set
            {
                this.uVPASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string UVPIS
        {
            get
            {
                return this.uVPISField;
            }
            set
            {
                this.uVPISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string UVWAS
        {
            get
            {
                return this.uVWASField;
            }
            set
            {
                this.uVWASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string UVPAK
        {
            get
            {
                return this.uVPAKField;
            }
            set
            {
                this.uVPAKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public string UVPIK
        {
            get
            {
                return this.uVPIKField;
            }
            set
            {
                this.uVPIKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public string UVWAK
        {
            get
            {
                return this.uVWAKField;
            }
            set
            {
                this.uVWAKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public string UVGEK
        {
            get
            {
                return this.uVGEKField;
            }
            set
            {
                this.uVGEKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=65)]
        public string CMPSM
        {
            get
            {
                return this.cMPSMField;
            }
            set
            {
                this.cMPSMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=66)]
        public string DCSTK
        {
            get
            {
                return this.dCSTKField;
            }
            set
            {
                this.dCSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=67)]
        public string VESTK
        {
            get
            {
                return this.vESTKField;
            }
            set
            {
                this.vESTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=68)]
        public string VLSTK
        {
            get
            {
                return this.vLSTKField;
            }
            set
            {
                this.vLSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=69)]
        public string RRSTA
        {
            get
            {
                return this.rRSTAField;
            }
            set
            {
                this.rRSTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=70)]
        public string BLOCK
        {
            get
            {
                return this.bLOCKField;
            }
            set
            {
                this.bLOCKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=71)]
        public string FSSTK
        {
            get
            {
                return this.fSSTKField;
            }
            set
            {
                this.fSSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=72)]
        public string LSSTK
        {
            get
            {
                return this.lSSTKField;
            }
            set
            {
                this.lSSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=73)]
        public string SPSTG
        {
            get
            {
                return this.sPSTGField;
            }
            set
            {
                this.sPSTGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=74)]
        public string PDSTK
        {
            get
            {
                return this.pDSTKField;
            }
            set
            {
                this.pDSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=75)]
        public string FMSTK
        {
            get
            {
                return this.fMSTKField;
            }
            set
            {
                this.fMSTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=76)]
        public string MANEK
        {
            get
            {
                return this.mANEKField;
            }
            set
            {
                this.mANEKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=77)]
        public string SPE_TMPID
        {
            get
            {
                return this.sPE_TMPIDField;
            }
            set
            {
                this.sPE_TMPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=78)]
        public string HDALL
        {
            get
            {
                return this.hDALLField;
            }
            set
            {
                this.hDALLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=79)]
        public string HDALS
        {
            get
            {
                return this.hDALSField;
            }
            set
            {
                this.hDALSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=80)]
        public string CMPS_CM
        {
            get
            {
                return this.cMPS_CMField;
            }
            set
            {
                this.cMPS_CMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=81)]
        public string CMPS_TE
        {
            get
            {
                return this.cMPS_TEField;
            }
            set
            {
                this.cMPS_TEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=82)]
        public string VBTYP_EXT
        {
            get
            {
                return this.vBTYP_EXTField;
            }
            set
            {
                this.vBTYP_EXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=83)]
        public string FSH_AR_STAT_HDR
        {
            get
            {
                return this.fSH_AR_STAT_HDRField;
            }
            set
            {
                this.fSH_AR_STAT_HDRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_ORDER
    {
        
        private string vBELNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string VBELN
        {
            get
            {
                return this.vBELNField;
            }
            set
            {
                this.vBELNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZWAS_IT_DP_ORDER_STATUS_BAPIResponse
    {
        
        private ZST_ORDER[] oRDERSField;
        
        private VBUK[] sTATUSESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZST_ORDER[] ORDERS
        {
            get
            {
                return this.oRDERSField;
            }
            set
            {
                this.oRDERSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public VBUK[] STATUSES
        {
            get
            {
                return this.sTATUSESField;
            }
            set
            {
                this.sTATUSESField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ord_status_Request_OUTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sami.com/DP", Order=0)]
        public PRDOrderStatusRequest.Ord_status_Request_IN Ord_status_Request_IN;
        
        public Ord_status_Request_OUTRequest()
        {
        }
        
        public Ord_status_Request_OUTRequest(PRDOrderStatusRequest.Ord_status_Request_IN Ord_status_Request_IN)
        {
            this.Ord_status_Request_IN = Ord_status_Request_IN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ord_status_Request_OUTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZWAS_IT_DP_ORDER_STATUS_BAPI.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ZWAS_IT_DP_ORDER_STATUS_BAPI.Response")]
        public PRDOrderStatusRequest.ZWAS_IT_DP_ORDER_STATUS_BAPIResponse ZWAS_IT_DP_ORDER_STATUS_BAPIResponse;
        
        public Ord_status_Request_OUTResponse()
        {
        }
        
        public Ord_status_Request_OUTResponse(PRDOrderStatusRequest.ZWAS_IT_DP_ORDER_STATUS_BAPIResponse ZWAS_IT_DP_ORDER_STATUS_BAPIResponse)
        {
            this.ZWAS_IT_DP_ORDER_STATUS_BAPIResponse = ZWAS_IT_DP_ORDER_STATUS_BAPIResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface Ord_status_Request_OUTChannel : PRDOrderStatusRequest.Ord_status_Request_OUT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Ord_status_Request_OUTClient : System.ServiceModel.ClientBase<PRDOrderStatusRequest.Ord_status_Request_OUT>, PRDOrderStatusRequest.Ord_status_Request_OUT
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Ord_status_Request_OUTClient(EndpointConfiguration endpointConfiguration) : 
                base(Ord_status_Request_OUTClient.GetBindingForEndpoint(endpointConfiguration), Ord_status_Request_OUTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Ord_status_Request_OUTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Ord_status_Request_OUTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Ord_status_Request_OUTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Ord_status_Request_OUTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Ord_status_Request_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PRDOrderStatusRequest.Ord_status_Request_OUTResponse PRDOrderStatusRequest.Ord_status_Request_OUT.Ord_status_Request_OUT(PRDOrderStatusRequest.Ord_status_Request_OUTRequest request)
        {
            return base.Channel.Ord_status_Request_OUT(request);
        }
        
        public PRDOrderStatusRequest.ZWAS_IT_DP_ORDER_STATUS_BAPIResponse Ord_status_Request_OUT(PRDOrderStatusRequest.Ord_status_Request_IN Ord_status_Request_IN)
        {
            PRDOrderStatusRequest.Ord_status_Request_OUTRequest inValue = new PRDOrderStatusRequest.Ord_status_Request_OUTRequest();
            inValue.Ord_status_Request_IN = Ord_status_Request_IN;
            PRDOrderStatusRequest.Ord_status_Request_OUTResponse retVal = ((PRDOrderStatusRequest.Ord_status_Request_OUT)(this)).Ord_status_Request_OUT(inValue);
            return retVal.ZWAS_IT_DP_ORDER_STATUS_BAPIResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PRDOrderStatusRequest.Ord_status_Request_OUTResponse> PRDOrderStatusRequest.Ord_status_Request_OUT.Ord_status_Request_OUTAsync(PRDOrderStatusRequest.Ord_status_Request_OUTRequest request)
        {
            return base.Channel.Ord_status_Request_OUTAsync(request);
        }
        
        public System.Threading.Tasks.Task<PRDOrderStatusRequest.Ord_status_Request_OUTResponse> Ord_status_Request_OUTAsync(PRDOrderStatusRequest.Ord_status_Request_IN Ord_status_Request_IN)
        {
            PRDOrderStatusRequest.Ord_status_Request_OUTRequest inValue = new PRDOrderStatusRequest.Ord_status_Request_OUTRequest();
            inValue.Ord_status_Request_IN = Ord_status_Request_IN;
            return ((PRDOrderStatusRequest.Ord_status_Request_OUT)(this)).Ord_status_Request_OUTAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://s049sappoprd.samipharma.com.pk:51100/XISOAPAdapter/MessageServlet?senderPa" +
                        "rty=&senderService=NSAP_PRD&receiverParty=&receiverService=&interface=Ord_status" +
                        "_Request_OUT&interfaceNamespace=http%3A%2F%2Fwww.sami.com%2FDP");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://s049sappoprd.samipharma.com.pk:51101/XISOAPAdapter/MessageServlet?senderP" +
                        "arty=&senderService=NSAP_PRD&receiverParty=&receiverService=&interface=Ord_statu" +
                        "s_Request_OUT&interfaceNamespace=http%3A%2F%2Fwww.sami.com%2FDP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
