//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesOrder
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_CREATE_SALE_ORDERException
    {
        
        private ZSD_CREATE_SALE_ORDERExceptionName nameField;
        
        private string textField;
        
        private ZSD_CREATE_SALE_ORDERExceptionMessage messageField;
        
        private ZSD_CREATE_SALE_ORDERExceptionAttributes attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZSD_CREATE_SALE_ORDERExceptionName Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ZSD_CREATE_SALE_ORDERExceptionMessage Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ZSD_CREATE_SALE_ORDERExceptionAttributes Attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public enum ZSD_CREATE_SALE_ORDERExceptionName
    {
        
        /// <remarks/>
        MANDATORY_FIELD_ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_CREATE_SALE_ORDERExceptionMessage
    {
        
        private string idField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_SALE_ORDER_CREATE_OUT
    {
        
        private string mATNRField;
        
        private string vBELNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATNR
        {
            get
            {
                return this.mATNRField;
            }
            set
            {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VBELN
        {
            get
            {
                return this.vBELNField;
            }
            set
            {
                this.vBELNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sami.com/SalesOrderCreation")]
    public partial class DisPortalRequestInMain
    {
        
        private string sNOField;
        
        private string iTEMNOField;
        
        private string pARTN_NUMBField;
        
        private string dOC_TYPEField;
        
        private string sALES_ORGField;
        
        private string dISTR_CHANField;
        
        private string dIVISIONField;
        
        private string pURCH_NOField;
        
        private string pURCH_DATEField;
        
        private string pRICE_DATEField;
        
        private string sT_PARTNField;
        
        private string mATERIALField;
        
        private string rEQ_QTYField;
        
        private string pLANTField;
        
        private string sTORE_LOCField;
        
        private string bATCHField;
        
        private string iTEM_CATEGField;
        
        private string oRD_REASONField;
        
        private string oRDERField;
        
        private string pO_ITEMField;
        
        private string yOUR_REFField;
        
        private string sALE_UNITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SNO
        {
            get
            {
                return this.sNOField;
            }
            set
            {
                this.sNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ITEMNO
        {
            get
            {
                return this.iTEMNOField;
            }
            set
            {
                this.iTEMNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PARTN_NUMB
        {
            get
            {
                return this.pARTN_NUMBField;
            }
            set
            {
                this.pARTN_NUMBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DOC_TYPE
        {
            get
            {
                return this.dOC_TYPEField;
            }
            set
            {
                this.dOC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SALES_ORG
        {
            get
            {
                return this.sALES_ORGField;
            }
            set
            {
                this.sALES_ORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DISTR_CHAN
        {
            get
            {
                return this.dISTR_CHANField;
            }
            set
            {
                this.dISTR_CHANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DIVISION
        {
            get
            {
                return this.dIVISIONField;
            }
            set
            {
                this.dIVISIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PURCH_NO
        {
            get
            {
                return this.pURCH_NOField;
            }
            set
            {
                this.pURCH_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PURCH_DATE
        {
            get
            {
                return this.pURCH_DATEField;
            }
            set
            {
                this.pURCH_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string PRICE_DATE
        {
            get
            {
                return this.pRICE_DATEField;
            }
            set
            {
                this.pRICE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ST_PARTN
        {
            get
            {
                return this.sT_PARTNField;
            }
            set
            {
                this.sT_PARTNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string MATERIAL
        {
            get
            {
                return this.mATERIALField;
            }
            set
            {
                this.mATERIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string REQ_QTY
        {
            get
            {
                return this.rEQ_QTYField;
            }
            set
            {
                this.rEQ_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string PLANT
        {
            get
            {
                return this.pLANTField;
            }
            set
            {
                this.pLANTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string STORE_LOC
        {
            get
            {
                return this.sTORE_LOCField;
            }
            set
            {
                this.sTORE_LOCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string BATCH
        {
            get
            {
                return this.bATCHField;
            }
            set
            {
                this.bATCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ITEM_CATEG
        {
            get
            {
                return this.iTEM_CATEGField;
            }
            set
            {
                this.iTEM_CATEGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ORD_REASON
        {
            get
            {
                return this.oRD_REASONField;
            }
            set
            {
                this.oRD_REASONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ORDER
        {
            get
            {
                return this.oRDERField;
            }
            set
            {
                this.oRDERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string PO_ITEM
        {
            get
            {
                return this.pO_ITEMField;
            }
            set
            {
                this.pO_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string YOUR_REF
        {
            get
            {
                return this.yOUR_REFField;
            }
            set
            {
                this.yOUR_REFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string SALE_UNIT
        {
            get
            {
                return this.sALE_UNITField;
            }
            set
            {
                this.sALE_UNITField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sami.com/SalesOrderCreation")]
    public partial class DisPortalRequestIn
    {
        
        private DisPortalRequestInMain[] iM_SALEDATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DisPortalRequestInMain[] IM_SALEDATA
        {
            get
            {
                return this.iM_SALEDATAField;
            }
            set
            {
                this.iM_SALEDATAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_CREATE_SALE_ORDERExceptionAttributes
    {
        
        private string v1Field;
        
        private string v2Field;
        
        private string v3Field;
        
        private string v4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string V1
        {
            get
            {
                return this.v1Field;
            }
            set
            {
                this.v1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string V2
        {
            get
            {
                return this.v2Field;
            }
            set
            {
                this.v2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string V3
        {
            get
            {
                return this.v3Field;
            }
            set
            {
                this.v3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string V4
        {
            get
            {
                return this.v4Field;
            }
            set
            {
                this.v4Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sami.com/SalesOrderCreation", ConfigurationName="SalesOrder.DisPortalPORequest_Out")]
    public interface DisPortalPORequest_Out
    {
        
        // CODEGEN: Generating message contract since the operation DisPortalPORequest_Out is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SalesOrder.ZSD_CREATE_SALE_ORDERException), Action="http://sap.com/xi/WebService/soap1.1", Name="ZSD_CREATE_SALE_ORDER.Exception", Namespace="urn:sap-com:document:sap:rfc:functions")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SalesOrder.DisPortalPORequest_OutResponse DisPortalPORequest_Out(SalesOrder.DisPortalPORequest_OutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<SalesOrder.DisPortalPORequest_OutResponse> DisPortalPORequest_OutAsync(SalesOrder.DisPortalPORequest_OutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_CREATE_SALE_ORDERResponse
    {
        
        private ZST_SALE_ORDER_CREATE_OUT[] eX_OUTPUTField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZST_SALE_ORDER_CREATE_OUT[] EX_OUTPUT
        {
            get
            {
                return this.eX_OUTPUTField;
            }
            set
            {
                this.eX_OUTPUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisPortalPORequest_OutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sami.com/SalesOrderCreation", Order=0)]
        public SalesOrder.DisPortalRequestIn DisPortalRequestIn;
        
        public DisPortalPORequest_OutRequest()
        {
        }
        
        public DisPortalPORequest_OutRequest(SalesOrder.DisPortalRequestIn DisPortalRequestIn)
        {
            this.DisPortalRequestIn = DisPortalRequestIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DisPortalPORequest_OutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZSD_CREATE_SALE_ORDER.Response", Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ZSD_CREATE_SALE_ORDER.Response")]
        public SalesOrder.ZSD_CREATE_SALE_ORDERResponse ZSD_CREATE_SALE_ORDERResponse;
        
        public DisPortalPORequest_OutResponse()
        {
        }
        
        public DisPortalPORequest_OutResponse(SalesOrder.ZSD_CREATE_SALE_ORDERResponse ZSD_CREATE_SALE_ORDERResponse)
        {
            this.ZSD_CREATE_SALE_ORDERResponse = ZSD_CREATE_SALE_ORDERResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DisPortalPORequest_OutChannel : SalesOrder.DisPortalPORequest_Out, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DisPortalPORequest_OutClient : System.ServiceModel.ClientBase<SalesOrder.DisPortalPORequest_Out>, SalesOrder.DisPortalPORequest_Out
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DisPortalPORequest_OutClient(EndpointConfiguration endpointConfiguration) : 
                base(DisPortalPORequest_OutClient.GetBindingForEndpoint(endpointConfiguration), DisPortalPORequest_OutClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DisPortalPORequest_OutClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DisPortalPORequest_OutClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DisPortalPORequest_OutClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DisPortalPORequest_OutClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DisPortalPORequest_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SalesOrder.DisPortalPORequest_OutResponse SalesOrder.DisPortalPORequest_Out.DisPortalPORequest_Out(SalesOrder.DisPortalPORequest_OutRequest request)
        {
            return base.Channel.DisPortalPORequest_Out(request);
        }
        
        public SalesOrder.ZSD_CREATE_SALE_ORDERResponse DisPortalPORequest_Out(SalesOrder.DisPortalRequestIn DisPortalRequestIn)
        {
            SalesOrder.DisPortalPORequest_OutRequest inValue = new SalesOrder.DisPortalPORequest_OutRequest();
            inValue.DisPortalRequestIn = DisPortalRequestIn;
            SalesOrder.DisPortalPORequest_OutResponse retVal = ((SalesOrder.DisPortalPORequest_Out)(this)).DisPortalPORequest_Out(inValue);
            return retVal.ZSD_CREATE_SALE_ORDERResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SalesOrder.DisPortalPORequest_OutResponse> SalesOrder.DisPortalPORequest_Out.DisPortalPORequest_OutAsync(SalesOrder.DisPortalPORequest_OutRequest request)
        {
            return base.Channel.DisPortalPORequest_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task<SalesOrder.DisPortalPORequest_OutResponse> DisPortalPORequest_OutAsync(SalesOrder.DisPortalRequestIn DisPortalRequestIn)
        {
            SalesOrder.DisPortalPORequest_OutRequest inValue = new SalesOrder.DisPortalPORequest_OutRequest();
            inValue.DisPortalRequestIn = DisPortalRequestIn;
            return ((SalesOrder.DisPortalPORequest_Out)(this)).DisPortalPORequest_OutAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://s049sappodev.samikhi.com:51000/XISOAPAdapter/MessageServlet?senderParty=&s" +
                        "enderService=NSAP_DEV&receiverParty=&receiverService=&interface=DisPortalPOReque" +
                        "st_Out&interfaceNamespace=http%3A%2F%2Fwww.sami.com%2FSalesOrderCreation");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://s049sappodev.samikhi.com:51001/XISOAPAdapter/MessageServlet?senderParty=&" +
                        "senderService=NSAP_DEV&receiverParty=&receiverService=&interface=DisPortalPORequ" +
                        "est_Out&interfaceNamespace=http%3A%2F%2Fwww.sami.com%2FSalesOrderCreation");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
