//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPPendingOrdersRequest
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.sami.com/DPPendingOrders", ConfigurationName="DPPendingOrdersRequest.DPPendingOrdersRequest_Out")]
    public interface DPPendingOrdersRequest_Out
    {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:sap-com:document:sap:rfc:functions) of message DPPendingOrdersRequest_OutRequest does not match the default value (https://www.sami.com/DPPendingOrders)
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse DPPendingOrdersRequest_Out(DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse> DPPendingOrdersRequest_OutAsync(DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZST_PENDING_ORDER_OUT
    {
        
        private string mATNRField;
        
        private decimal kWMENGField;
        
        private bool kWMENGFieldSpecified;
        
        private decimal lFIMGField;
        
        private bool lFIMGFieldSpecified;
        
        private decimal pENDINGField;
        
        private bool pENDINGFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATNR
        {
            get
            {
                return this.mATNRField;
            }
            set
            {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal KWMENG
        {
            get
            {
                return this.kWMENGField;
            }
            set
            {
                this.kWMENGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KWMENGSpecified
        {
            get
            {
                return this.kWMENGFieldSpecified;
            }
            set
            {
                this.kWMENGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal LFIMG
        {
            get
            {
                return this.lFIMGField;
            }
            set
            {
                this.lFIMGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LFIMGSpecified
        {
            get
            {
                return this.lFIMGFieldSpecified;
            }
            set
            {
                this.lFIMGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal PENDING
        {
            get
            {
                return this.pENDINGField;
            }
            set
            {
                this.pENDINGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PENDINGSpecified
        {
            get
            {
                return this.pENDINGFieldSpecified;
            }
            set
            {
                this.pENDINGFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZSD_GET_PENDING_ORDERS", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class DPPendingOrdersRequest_OutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IV_DISTRIBUTOR;
        
        public DPPendingOrdersRequest_OutRequest()
        {
        }
        
        public DPPendingOrdersRequest_OutRequest(string IV_DISTRIBUTOR)
        {
            this.IV_DISTRIBUTOR = IV_DISTRIBUTOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ZSD_GET_PENDING_ORDERS.Response", WrapperNamespace="urn:sap-com:document:sap:rfc:functions", IsWrapped=true)]
    public partial class DPPendingOrdersRequest_OutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DPPendingOrdersRequest.ZST_PENDING_ORDER_OUT[] E_ORDERS;
        
        public DPPendingOrdersRequest_OutResponse()
        {
        }
        
        public DPPendingOrdersRequest_OutResponse(DPPendingOrdersRequest.ZST_PENDING_ORDER_OUT[] E_ORDERS)
        {
            this.E_ORDERS = E_ORDERS;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DPPendingOrdersRequest_OutChannel : DPPendingOrdersRequest.DPPendingOrdersRequest_Out, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DPPendingOrdersRequest_OutClient : System.ServiceModel.ClientBase<DPPendingOrdersRequest.DPPendingOrdersRequest_Out>, DPPendingOrdersRequest.DPPendingOrdersRequest_Out
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DPPendingOrdersRequest_OutClient(EndpointConfiguration endpointConfiguration) : 
                base(DPPendingOrdersRequest_OutClient.GetBindingForEndpoint(endpointConfiguration), DPPendingOrdersRequest_OutClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DPPendingOrdersRequest_OutClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DPPendingOrdersRequest_OutClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DPPendingOrdersRequest_OutClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DPPendingOrdersRequest_OutClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DPPendingOrdersRequest_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse DPPendingOrdersRequest.DPPendingOrdersRequest_Out.DPPendingOrdersRequest_Out(DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest request)
        {
            return base.Channel.DPPendingOrdersRequest_Out(request);
        }
        
        public DPPendingOrdersRequest.ZST_PENDING_ORDER_OUT[] DPPendingOrdersRequest_Out(string IV_DISTRIBUTOR)
        {
            DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest inValue = new DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest();
            inValue.IV_DISTRIBUTOR = IV_DISTRIBUTOR;
            DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse retVal = ((DPPendingOrdersRequest.DPPendingOrdersRequest_Out)(this)).DPPendingOrdersRequest_Out(inValue);
            return retVal.E_ORDERS;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse> DPPendingOrdersRequest.DPPendingOrdersRequest_Out.DPPendingOrdersRequest_OutAsync(DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest request)
        {
            return base.Channel.DPPendingOrdersRequest_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task<DPPendingOrdersRequest.DPPendingOrdersRequest_OutResponse> DPPendingOrdersRequest_OutAsync(string IV_DISTRIBUTOR)
        {
            DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest inValue = new DPPendingOrdersRequest.DPPendingOrdersRequest_OutRequest();
            inValue.IV_DISTRIBUTOR = IV_DISTRIBUTOR;
            return ((DPPendingOrdersRequest.DPPendingOrdersRequest_Out)(this)).DPPendingOrdersRequest_OutAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://s049sappodev.samikhi.com:51000/XISOAPAdapter/MessageServlet?senderParty=&s" +
                        "enderService=NSAP_DEV&receiverParty=&receiverService=&interface=DPPendingOrdersR" +
                        "equest_Out&interfaceNamespace=https%3A%2F%2Fwww.sami.com%2FDPPendingOrders");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://s049sappodev.samikhi.com:51001/XISOAPAdapter/MessageServlet?senderParty=&" +
                        "senderService=NSAP_DEV&receiverParty=&receiverService=&interface=DPPendingOrders" +
                        "Request_Out&interfaceNamespace=https%3A%2F%2Fwww.sami.com%2FDPPendingOrders");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
